name: debian-11.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Octopus 11.1 on Debian in Docker
      run: make debian-11.1
      
