name: debian-octopusdevelop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
     - cron:  '0 10 * * MON'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Octopus develop on Debian in Docker
      run: make debian-octopusdevelop
      
